# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://handle08:<db_password>@clusterdb.ofpkg9o.mongodb.net/TicketRush?retryWrites=true&w=majority

# JWT config
jwt.secret=DayLaChuoiBiMatCuaRiengToi2026
jwt.expiration=86400000

# Server port
server.port=8080
